Gdevelop-game/GDevelop-Open-Game

src/game.json
src/layouts/intro.json
src/layouts/menu.json
src/layouts/overworld.json
src/layouts/rooms.json

Adds:
- Intro Scene
- Menu Scene
- Overworld Scene
- Rooms Scene

Add basic scenes

---

.github/workflows/main.yml
build/.gitignore
build/build.js
build/package-lock.json
build/package.json

Adds flexibility by introducing a system able to potentially modify files before and after the export

Refactor build system

---

build/.gitignore
build/build.js
build/build_electron.js
build/build_web.js
build/customLoadingScreen/loadingscreen-pixi-renderer.js
build/package.json

- Merge build types electron and web
- Add custom loading screen file
- Add custom loading screen to build pipeline

add custom loading screen

---

build/build.js
build/customHtml/index.html
build/workboxCache/sw.js

Permits offline use by storing files in cache and using cache if network unreachable

Add caching

---

companion-app/package.json
companion-app/src/AppsManager/App.js
companion-app/src/AppsManager/Apps/Hello.jsx
companion-app/src/AppsManager/Apps/Maps.jsx
companion-app/src/AppsManager/AppsLister.tsx
companion-app/src/AppsManager/AppsManager.jsx
companion-app/src/Main/Main.jsx
companion-app/src/react-app-env.d.ts
companion-app/tsconfig.json
companion-app/webpack.config.js
companion-app/yarn.lock

Begin to fill in features of the Companion App

Add features to companion app

---

src/externalEvents/niko.json
src/game.json
src/layouts/overworld.json
src/layouts/rooms.json

1. changed name to weapon system
2. improoved gun4(sniper)
3. added a timer thing so the bullet will be deleted(differnt gun differnt time)

changes to gun system

---

companion-app/src/Components/Connect.jsx

Added a simple spinner in the connection menu.

---

companion-app/src/Components/Connect.jsx
companion-app/src/Main/Main.jsx

Adds a notification on disconnection and catch more disconnections scenarios

Improve disconnection from Companion

---

src/game.json
src/layouts/overworld.json

texture/object bug fixes for the tazer

fixes for tazer

---

src/game.json
src/layouts/overworld.json

modified map one and some minor changes

modified the map 1

---

src/layouts/overworld.json

modified map 1

---

src/externalEvents/niko.json
src/game.json
src/layouts/overworld.json

(well i dont call it a bug but still)

fixed the bug with guns and water

---

src/externalEvents/niko.json
src/externalEvents/phone.json
src/game.json
src/layouts/overworld.json

new controls:
v = adding to weapon wheel
b = using from weapon wheel
new feature:
u c an now press a number to go to that weapon wheel thing(1 to 5)

new controls for weapon wheel and added a new feature to weapon wheel

---

src/game.json
src/layouts/menu.json
src/layouts/settings.json

Add the anchor behavior to the UI in menu and settings.

Add anchor to UI

---

src/game.json

Menu scene was deleted due to issues with the mouse and would hopefully be added in soon.

deleted menu scene

---

companion-app/package.json
companion-app/src/Components/Connect.jsx
companion-app/src/Components/MenuButton.jsx
companion-app/src/Main/Main.jsx
companion-app/src/PhoneApps/App.js
companion-app/src/PhoneApps/Apps/Hello.jsx
companion-app/src/PhoneApps/Apps/Maps.jsx
companion-app/src/PhoneApps/Apps/SayHi.jsx
companion-app/src/PhoneApps/AppsLister.tsx
companion-app/src/PhoneApps/AppsManager.jsx
companion-app/src/index.js
companion-app/src/serviceWorker.js
companion-app/src/setupTests.js
companion-app/yarn.lock

- Added prettier to dev dependencies and ran it
- Changed a redundant if block to a ternary
- Updated react-scripts

Clean up companion app

---

src/layouts/rooms.json

Before the pivot point was not same on all animations, then now the same pivot is setup everywhere.

Fix pivot for the player with all weapons

---

README.md

Added Contributors Name to the readme.

Added Contributors to the readme

---

src/layouts/overworld.json
src/layouts/rooms.json

Fixed Rooms

---

.github/workflows/main.yml

Fixes auto build. See test run here: https://github.com/Gdevelop-game/GDevelop-Open-Game/actions/runs/413393357

Try fix auto build

---

README.md

adding support button in readme

Add ko-fi support button

---

build/build.js
build/package.json
build/pwa/sw-web.js
build/pwa/sw.js
build/yarn.lock

Rework the build pipeline to add nice spinners and use GDExporter v3 which can autoupdate the GDevelop runtime itself.

Rework build pipeline

---

.gitignore
src/.gitignore

Add os generated files to gitignore
this files include :
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
ehthumbs.db
Thumbs.db

OS generated files to gitignore
